services:
  simple_rop:
    build: .
    ports:
      - "1344:1344"
    restart: unless-stopped
    
    read_only: true
    
    cap_drop:
      - ALL
      
    security_opt:
      - no-new-privileges:true
      
    pids_limit: 50

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M