services:
  int_chal:
    build: .
    ports:
      - "1339:1339"
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true