services:
  stack1:
    build: .
    ports:
      - "1340:1340"
    environment:
      - FLAG=flag{W0W_f1rst_overfl0w}
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true